% Splitting updater
function state = UpdateStateZone3(t,state,alpha,beta_left,beta_centre,beta_right,...
                gamma_centre,tau,tau_h,gh,gs,I,V_r,N)
            
  v0 = state(1);
  n0 = state(2);
  u0 = state(3);
  y0 = state(4);
  
  fv = (v0*exp(-t/tau)...
  +(beta_right*gh*(tau-tau_h+tau_h*exp(-t/tau_h)))/(tau-tau_h)...
  -(beta_right*gh*tau*exp(-t/tau))/(tau-tau_h)...
  -(gh*n0*tau_h*exp(-t/tau_h))/(tau-tau_h)...
  +(gh*n0*tau_h*exp(-t/tau))/(tau-tau_h)...
  +(gs*exp(-alpha*t).*(alpha*tau*u0-u0-alpha*t*y0+alpha*tau*y0+alpha^2*t*tau*y0))/(alpha*tau-1)^2 ...
  -(gs*exp(-t/tau)*(alpha*tau*u0-u0+alpha*tau*y0))/(alpha*tau-1)^2 ...
  -I+I*exp(-t/tau));
  fn = beta_right*(1-exp(-t/tau_h))+n0*exp(-t/tau_h));
  fu = (u0+alpha*y0*t).*exp(-alpha*t);
  fy = y0*exp(-alpha*t);
  
  state = [fv;fn;fu;fy];
  
end